import localFont from "next/font/local";
import "./fonts.css";
import {Secular_One} from "next/font/google"
import "./globals.css";
import CustomCursor from "./components/CustomCursor";


const secular = Secular_One({
  weight: "400",
  subsets: ["latin"],
});

const galactic = localFont({
  src: "./fonts/galacticondensed-regular-ffc-web.woff",
  variable: "--font-galactic",
  weight: "100 900",
});

export const metadata = {
  title: "Chlomo's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${galactic.variable} ${secular.variable} antialiased font-secular`}
      >
        {children}
        <CustomCursor />
      </body>
    </html>
  );
}
